uid=$(id -u)
gid=$(id -g)

echo "Creating Dockerfile from template"

echo "# Generated by setup.sh" > Dockerfile
sed -e "s/{UID}/$uid/" -e "s/{GID}/$gid/" Dockerfile.template >> Dockerfile

nvidia_version=$(find /usr/lib -maxdepth 1 -type d | sed -n "s/^\/usr\/lib\/nvidia-\([0-9]*\)$/\1/p")

echo "Adding NVIDIA driver number to the container."
if [ "${#nvidia_version[@]}" -gt 1 ]; then
  echo "Multiple versions of NVIDIA driver found: $nvidia_version"
  read -p 'Enter version to use (if unclear, try the max): ' ver
elif [ "${#nvidia_version[@]}" -lt 1 ]; then
  echo "Couldn't find driver version number, contact mushr@cs.washington.edu for help"
  exit 1
else
  ver=${nvidia_version[0]}
fi

sed "s/{DRIVER_VERSION}/$ver/" .env.template > .env

