uid=$(id -u)
gid=$(id -g)

echo "Creating Dockerfile from template"

echo "# Generated by setup.sh" > Dockerfile
sed -e "s/{UID}/$uid/" -e "s/{GID}/$gid/" Dockerfile.template >> Dockerfile

nvidia_version=$(find /usr/lib -maxdepth 1 -type d | sed -n "s/^\/usr\/lib\/nvidia-\([0-9]*\)$/\1/p")
IFS=$'\n' read -r -d '' -a nvidia_v_array <<< "$nvidia_version"

echo "Adding NVIDIA driver number to the container."

if [ "${#nvidia_v_array[@]}" -gt 1 ]; then
  echo "Multiple versions of NVIDIA driver found: ${nvidia_v_array[@]}"
  read -p 'Enter version to use (if unclear, try the max): ' ver
elif [ "${#nvidia_v_array[@]}" -lt 1 ]; then
  echo "Couldn't find driver version number, consult FAQ and get in contact at mushr.io"
  exit 1
else
  ver=${nvidia_v_array[0]}
fi

sed "s/{DRIVER_VERSION}/$ver/" .env.template > .env
